[package]
name = "zoog"
version = "0.1.0"
authors = ["Francis Russell <francis@unchartedbackwaters.co.uk>"]
edition = "2018"
homepage = "https://github.com/FrancisRussell/zoog"
readme = "README.md"
repository = "https://github.com/FrancisRussell/zoog.git"
license-file = "LICENSE"
keywords = ["opus", "normalization"]
description = "Modifies Opus output gain values and R128 tags"

[dependencies]
byteorder = "1.3.4"
derivative = "2.1.1"
ogg = "0.7.1"
tempfile = "3.1.0"
thiserror = "1.0.23"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = [ "wrap_help" ]
