[package]
name = "zoog"
version = "0.1.0"
authors = ["Francis Russell <francis@unchartedbackwaters.co.uk>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
clap = "2.33.3"
derivative = "2.1.1"
ogg = "0.7.1"
tempfile = "3.1.0"
thiserror = "1.0.23"
