on: [push]

name: Continuous integration

jobs:
  check-builds:
    name: Check builds for all platforms
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
        platform: [ubuntu-latest]
        include:
          - target: x86_64-apple-darwin
            platform: macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with: 
          use-cross: true
          command: build
          args: --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: zoog-debug-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/debug/zoog
            target/${{ matrix.target }}/debug/zoog.exe
          if-no-files-found: error

  cargo-test:
    name: Run Cargo test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
